const MEDIA = {
    "Adelie Penguin": {"image": "9k9tNQTwMEA","video": "YKqXGNNPNaQ" },
    "Agama Lizard": {"image": "qs2chAlF4Vw","video": "bWKfQFz0LZo" },
    "Albatross": {"image": "2-V81Lpns50","video": "vZDwTEpOc-4" },
    "Alligator": {"image": "POKb4uUOizU","video": "0wRdFr1t7iI" },
    "Alpaca": {"image": "yt39XjxwGUE","video": "X0bE86akgmw" },
    "Arctic Fox": {"image": "NBvcQRdRSeQ","video": "C7mxTEskjQg" },
    "Assassin Bug": {"image": "_-zdhg6yKZ4","video": "Iqhp69whyEE" },
    "Axolotl": {"image": "_o-S-UmtT4Y","video": "REeEf8L2PrU" },
    "Baboon": {"image": "or59VX6vVsI","video": "gL-hy4uKZNs" },
    "Bald Eagle": {"image": "ys4najRQRkA","video": "BEgEIEfSuvU" },
    "Banana Ball Python": {"image": "SGW7enB7bl0","video": "0gPsaLimhj0" },
    "Barn Owl": {"image": "F66E2VdboAY","video": "dnh5rte28lQ" },
    "Bearded Vulture": {"image": "tOAl-2-Xi3w","video": "cp7waMP5xQo" },
    "Beaver": {"image": "DqMA8B7f7pQ","video": "oL5SD6z7AG8" },
    "Bee": {"image": "yxXpjF-RrnA","video": "ta154f5Rp5Y" },
    "Bengal Tiger": {"image": "037fCBgZB10","video": "HVeIo0JaAZQ" },
    "Bison": {"image": "FXiHwsskusY","video": "iVO5mkIn1c" },
    "Black Rhinoceros": {"image": "GGuPS7sfbtY","video": "ST_83Hkrbk4" },
    "Black-Footed Ferret": {"image": "hn0AtxarNNw","video": "aAFFJcB02DA" },
    "Blue-Ringed Octopus": {"image": "tFBjYVy9CwQ","video": "m34kHdq9EB4" },
    "Bobcat": {"image": "ND8mP8__0qs","video": "IOfbRzg4bQ4" },
    "Box Turtle": {"image": "HySH5_y95iQ","video": "V6PH-DM3jeQ" },
    "Burrowing Owl": {"image": "n6I2GT_Pij4","video": "3AbWqvF8pSs" },
    "Camel": {"image": "P3gDo8yUA8g","video": "gEKXM_YH_kI" },
    "Caribou": {"image": "9lau4mL-FAE","video": "EQiip3xuxNY" },
    "Cheetah": {"image": "bcJUbYd5gTo","video": "J20eXhZTHEo" },
    "Clownfish": {"image": "d4PoLtbLinU","video": "hwtLABCaZbs" },
    "Coral Snake": {"image": "","video": "xVmvCpiFz7I" },
    "Crocodile": {"image": "YOX8ZMTo7hk","video": "0wRdFr1t7iI" },
    "Deer": {"image": "K_Na5gCmh38","video": "RqF23YEoPEs" },
    "Desert Tortoise": {"image": "pINxk0ZU1dg","video": "r9pAaTDIri0" },
    "Dingo": {"image": "8qOh0vBS5B8","video": "1F-qgDAAGdI" },
    "Dolphin": {"image": "K6kZKJOmZrk","video": "VjMn_dVCJyA" },
    "Dragonfly": {"image": "EJVrmuzBGiA","video": "lxubbepoz7Q" },
    "Earthworm": {"image": "","video": "0ZYIZ4J4PZ8" },
    "Eel": {"image": "yBraeHiDXi8","video": "fdR93OhxdCI" },
    "Elephant": {"image": "P7L5011nD5s","video": "Aw6GkiCvcWs" },
    "Elephant Seal": {"image": "dFL06nNdcsM","video": "vh56Kq4L7nY" },
    "Elk": {"image": "lQ0gPL_0Bt8","video": "u_1rOM5roEM" },
    "Emu": {"image": "6AI-OcfLkwA","video": "54P_wgNyFuQ" },
    "Flamingo": {"image": "wTPp323zAEw","video": "QLV_K7DVeyU" },
    "Flounder": {"image": "jS0Yfz-qQLw","video": "EIMRSt40OMk" },
    "Fox": {"image": "/xUUZcpQlqpM","video": "Az7NlYBsUp0" },
    "Frog": {"image": "7-bpTcGz5uM","video": "g9RkRyvjF2s" },
    "Fruit Bat": {"image": "8cw5JIEFnwE","video": "NBCODnTUOrY" },
    "Galapagos Tortoise": {"image": "1tIkmgkpfNQ","video": "kXISZx1TNJY" },
    "Gazelle": {"image": "Y5Kjgbd3hKA","video": "Ms7cMyeXA8M" },
    "Gecko": {"image": "gZPH6r_UvSk","video": "0o5j3__-fa0" },
    "Giraffe": {"image": "LK4qTPvWdnM","video": "P_ckAbOr0r4" },
    "Glass Frog": {"image": "6PTp9C8Csjk","video": "jAQPSHvNB4A" },
    "Golden Lion Tamarin": {"image": "5uIkDWUQ8io","video": "WLDce0kUSSc" },
    "Gorilla": {"image": "j-LQfH_zjX8","video": "rHhSCO5-3Pg" },
    "Hammerhead Shark": {"image": "Ei6M0MtQQU8","video": "YCZwTJ-AFeA" },
    "Hawaiian Goose": {"image": "VKN7LWnpTMQ","video": "mhuKPw6yzyE" },
    "Heron": {"image": "EysCLgycVgc","video": "droo7sFCuIQ" },
    "Hippopotamus": {"image": "JWlY4Z4_mCI","video": "aftXiUpsXrg" },
    "Howler Monkey": {"image": "3GsHYJFe-qI","video": "REPoVfN-Ij4" },
    "Hummingbird": {"image": "hjmED1qivmc","video": "Hn87hCEpO7I" },
    "Humpback Whale": {"image": "JRsl_wfC-9A","video": "TGPLv0e0x0E" },
    "Ibex": {"image": "WCspLqRy5MU","video": "0RnPX5s7-fE" },
    "Ibis": {"image": "ZRsX3uoQxNY","video": "Mj9OiKGoPcc" },
    "Iguana": {"image": "ssAcdlJRsI4","video": "zSz4DSsg7C8" },
    "Impala": {"image": "M03OCZvYSxY","video": "OfQe6i7Xx0o" },
    "Jackrabbit": {"image": "o4kAhL2X3Wk","video": "u7xsWgsQioc" },
    "Jackson’s Chameleon": {"image": "nMJKAXHBLLI","video": "zW9PHJiB6Xo" },
    "Jaguar": {"image": "gkBthB89xMs","video": "DHmDOJrNE0M" },
    "Jellyfish": {"image": "5fhcbkOPhwA","video": "9z8ujpPgUjI" },
    "Kangaroo": {"image": "2f33ykzzPCU","video": "-nQzs_4WhO0" },
    "Kestrel": {"image": "UfyDkU1uVX0","video": "54HJdMHZpgs" },
    "King Cobra": {"image": "bPldxRHkTzw","video": "ImUgAzHSyIc" },
    "Kingfisher": {"image": "7xQW7I9flYk","video": "IA_FtJziPto" },
    "Kiwi": {"image": "","video": "rb9aW2GYE24" },
    "Koala": {"image": "CIMk0FSOrAE","video": "oI3ADcDH0Uc" },
    "Komodo Dragon": {"image": "W0-3v369lrE","video": "MJzcGu_5FCY" },
    "Ladybug": {"image": "Ap0alm8xpxw","video": "5ccCLbwmv9o" },
    "Leatherback Sea Turtle": {"image": "Xchp9dzP0ao","video": "UW-rcxcONYY" },
    "Lemur": {"image": "83gB_koMuvA","video": "mlObl4sJcG4" },
    "Leopard": {"image": "3TwThGdEUZA","video": "uxPMj-lq_aA" },
    "Lion": {"image": "UxHol6SwLyM","video": "L5YHlH0f4Uw" },
    "Llama": {"image": "yt39XjxwGUE","video": "AxrslX3YdGs" },
    "Lobster": {"image": "p1D68SxmdtY","video": "QjBB46McM4o" },
    "Macaque": {"image": "gYSHsshVZLM","video": "vb19RxMqa0A" },
    "Macaroni Penguin": {"image": "Cj7cnWptYiI","video": "pltbjRdtUX0" },
    "Manatee": {"image": "udSP7GCxw3w","video": "J2HXFjnnr2A" },
    "Manta Ray": {"image": "Syzn3nfkYE4","video": "DVQH7a9ekcg" },
    "Marmot": {"image": "iyg1Otnket8","video": "NJXi3s59sn0" },
    "Moose": {"image": "MVIqwQvkwG4","video": "OrmxZCzYGSw" },
    "Narwhal": {"image": "","video": "MXsZg1sQYvA" },
    "North American Black Bear": {"image": "lWHvAw1Inbs","video": "QaRGgipzehU" },
    "Northern Cardinal": {"image": "Yu_ejF2s_dI","video": "dvrAF2XWizo" },
    "Nudibranch": {"image": "pymDKmTB7wk","video": "yE4yDALUVV4" },
    "Numbat": {"image": "","video": "lrxD27Yyl-c" },
    "Octopus": {"image": "dW0gfo__uU8","video": "oSyEZAm8nb8" },
    "Orang-utan": {"image": "8_5sEk7Ay18","video": "6WpryDlmj2M" },
    "Ostrich": {"image": "qeGHu5Jdy5s","video": "pfVNsGFlCpY" },
    "Otter": {"image": "mhXop68UAGk","video": "crM258UlVjA" },
    "Oyster": {"image": "uC5ilONVVtg","video": "hevtQVHYE20" },
    "Painted Turtle": {"image": "w4tjvHHcwbg","video": "E6jQn9SsAY0" },
    "Panther": {"image": "MZVJ4joUAlI","video": "QQ1AaTz5p9w" },
    "Parrotfish": {"image": "X-_vjB4_tdM","video": "joqVD1kLebU" },
    "Platypus": {"image": "Vv019m_ClpY","video": "QNoQvjlmGdk" },
    "Polar Bear": {"image": "Ec_ygZTIv_0","video": "XdCaBF8NJ00" },
    "Porcupine": {"image": "na4VeTI5c-0","video": "ZphlCdI2yqA" },
    "Proboscis Monkey": {"image": "H0x10qmw9Zc","video": "JDYstx7znOc" },
    "Quetzal": {"image": "cvO95LohoQg","video": "NZEmaz-xsmQ" },
    "Quokka": {"image": "4cT6YwMkHyg","video": "e_cOVTqLNng" },
    "Rabbit": {"image": "KvHT4dltPEQ","video": "JtzeTeoyKfI" },
    "Red Panda": {"image": "e8t9o3eJ36o","video": "AQollRmWAr4" },
    "Reef Shark": {"image": "ZEr3XTwFxxE","video": "T_qCD3EF0vU" },
    "Robin": {"image": "3lGi0BXJ1W0","video": "qGz-pO0QTN4" },
    "Roseate Spoonbill": {"image": "WP0ZP9pFywU","video": "HsTWcFpcKnM" },
    "Salamander": {"image": "CcZW_zuuCGk","video": "TpLPkreZvFA" },
    "Scarlet Macaw": {"image": "vIx55PnjL58","video": "vDQsxgXxhmw" },
    "Sea Anemone": {"image": "2cU7jvnjYhk","video": "w3DiDUERdso" },
    "Sea Dragon": {"image": "6NSWCndscrE","video": "5u1Elzzw0_0" },
    "Seahorse": {"image": "n6cvkHh0xmE","video": "XqP0xqbnAMU" },
    "Skunk": {"image": "jG8eaA5Iq3A","video": "_VFm7oOq0LE" },
    "Sloth": {"image": "E1UfNaIQMSY","video": "ndMKTnSRsKM" },
    "Squid": {"image": "j8BRxbtTwTQ","video": "Sy1WFSIeYOU" },
    "Stork": {"image": "biJCd2N-1ms","video": "lOyPeUJbUXU" },
    "Tapir": {"image": "ZgJVo64oBUM","video": "M7FnvV1zCGk" },
    "Tiger": {"image": "Fbdr6gXJBVY","video": "8OmRW4em_vA" },
    "Tiger Shark": {"image": "GBDkr3k96DE","video": "YIiCo15ol7g" },
    "Tree Frog": {"image": "JLMEZxBcXCU","video": "9Zq4gD6MelM" },
    "Tropicbird": {"image": "","video": "0WR-bKcrvMQ" },
    "Uakari": {"image": "","video": "r_mB-23z4To" },
    "Umbrellabird": {"image": "","video": "HKRtODqdwEU" },
    "Vervet Monkey": {"image": "rTEt2xxdOvI","video": "Ji-jFWtlmoM" },
    "Vicuña": {"image": "OXPFrEwRlv0","video": "n0EieDNfhxs" },
    "Vulture": {"image": "X_focRRR0Uw","video": "U7bL-h8Cfyc" },
    "Walrus": {"image": "h13Y8vyIXNU","video": "5BT7KkKAZC8" },
    "Warthog": {"image": "6GOGynHxL74","video": "niiYPegpP4M" },
    "Whale Shark": {"image": "Abj_zUko6Mg","video": "1ztPeCZ6SPo" },
    "White-Faced Capuchin": {"image": "5UGhVm_YDdg","video": "OkkkPAE9KvE" },
    "Wolf": {"image": "1AIYdIb3O5M","video": "zufoCVXHyF0" },
    "X-Ray Tetra": {"image": "","video": "8gF0QaTcYro" },
    "Xerus": {"image": "WuZKOVtnvC8","video": "XuvMr1gkI_k" },
    "Yak": {"image": "PQgD2Mjrjpw","video": "lMhRJkUXVZo" },
    "Yellow Anaconda": {"image": "XY1iezxiFhw","video": "LY3u_oxqf3o" },
    "Yellowfin Tuna": {"image": "jKbhB5Qh-9k","video": "bidCU-NSA-M" },
    "Zebra": {"image": "UgidX4V13Gc","video": "kWxnadQI5Qw" },
    "Zebra Finch": {"image": "M9YOf_w6uiE","video": "jJHzUCfTKfY" },
    "Zebra Mussels": {"image": "","video": "tvPdie2FVK0" },
    "Zebu": {"image": "Sn4YhNxvPcM","video": "BG0fFDhIiv8" }
}


module.exports = MEDIA;