const MEDIA =  {
    "Adelie Penguin": {"image": "9k9tNQTwMEA","video": "YKqXGNNPNaQ" },
    "Agama Lizard": {"image": "qs2chAlF4Vw","video": "" },
    "Albatross": {"image": "2-V81Lpns50","video": "" },
    "Alligator": {"image": "POKb4uUOizU","video": "" },
    "Alpaca": {"image": "yt39XjxwGUE","video": "X0bE86akgmw" },
    "Arctic Fox": {"image": "NBvcQRdRSeQ","video": "" },
    "Assassin Bug": {"image": "_-zdhg6yKZ4","video": "" },
    "Axolotl": {"image": "_o-S-UmtT4Y","video": "" },
    "Baboon": {"image": "or59VX6vVsI","video": "" },
    "Bald Eagle": {"image": "ys4najRQRkA","video": "" },
    "Banana Ball Python": {"image": "SGW7enB7bl0","video": "" },
    "Barn Owl": {"image": "F66E2VdboAY","video": "" },
    "Bearded Vulture": {"image": "tOAl-2-Xi3w","video": "" },
    "Beaver": {"image": "DqMA8B7f7pQ","video": "" },
    "Bee": {"image": "yxXpjF-RrnA","video": "" },
    "Bengal Tiger": {"image": "037fCBgZB10","video": "" },
    "Bison": {"image": "FXiHwsskusY","video": "" },
    "Black Rhinoceros": {"image": "GGuPS7sfbtY","video": "" },
    "Black-Footed Ferret": {"image": "hn0AtxarNNw","video": "" },
    "Blue-Ringed Octopus": {"image": "tFBjYVy9CwQ","video": "" },
    "Bobcat": {"image": "ND8mP8__0qs","video": "" },
    "Box Turtle": {"image": "HySH5_y95iQ","video": "" },
    "Burrowing Owl": {"image": "n6I2GT_Pij4","video": "" },
    "Camel": {"image": "P3gDo8yUA8g","video": "" },
    "Caribou": {"image": "9lau4mL-FAE","video": "" },
    "Cheetah": {"image": "bcJUbYd5gTo","video": "J20eXhZTHEo" },
    "Clownfish": {"image": "d4PoLtbLinU","video": "" },
    "Crocodile": {"image": "YOX8ZMTo7hk","video": "" },
    "Deer": {"image": "K_Na5gCmh38","video": "" },
    "Desert Tortoise": {"image": "pINxk0ZU1dg","video": "" },
    "Dingo": {"image": "8qOh0vBS5B8","video": "" },
    "Dolphin": {"image": "K6kZKJOmZrk","video": "" },
    "Dragonfly": {"image": "EJVrmuzBGiA","video": "" },
    "Earthworm": {"image": "","video": "" },
    "Eel": {"image": "yBraeHiDXi8","video": "" },
    "Elephant": {"image": "P7L5011nD5s","video": "" },
    "Elephant Seal": {"image": "dFL06nNdcsM","video": "" },
    "Elk": {"image": "lQ0gPL_0Bt8","video": "" },
    "Emu": {"image": "6AI-OcfLkwA","video": "" },
    "Flamingo": {"image": "wTPp323zAEw","video": "" },
    "Flounder": {"image": "jS0Yfz-qQLw","video": "" },
    "Fox": {"image": "/xUUZcpQlqpM","video": "" },
    "Frog": {"image": "7-bpTcGz5uM","video": "" },
    "Fruit Bat": {"image": "8cw5JIEFnwE","video": "" },
    "Galapagos Tortoise": {"image": "1tIkmgkpfNQ","video": "" },
    "Gazelle": {"image": "Y5Kjgbd3hKA","video": "" },
    "Gecko": {"image": "gZPH6r_UvSk","video": "" },
    "Giraffe": {"image": "LK4qTPvWdnM","video": "" },
    "Golden Lion Tamarin": {"image": "5uIkDWUQ8io","video": "" },
    "Gorilla": {"image": "j-LQfH_zjX8","video": "" },
    "Hammerhead Shark": {"image": "Ei6M0MtQQU8","video": "" },
    "Hawaiian Goose": {"image": "VKN7LWnpTMQ","video": "" },
    "Heron": {"image": "EysCLgycVgc","video": "" },
    "Hippopotamus": {"image": "JWlY4Z4_mCI","video": "" },
    "Howler Monkey": {"image": "3GsHYJFe-qI","video": "" },
    "Hummingbird": {"image": "hjmED1qivmc","video": "" },
    "Humpback Whale": {"image": "JRsl_wfC-9A","video": "" },
    "Ibex": {"image": "WCspLqRy5MU","video": "" },
    "Ibis": {"image": "ZRsX3uoQxNY","video": "" },
    "Iguana": {"image": "ssAcdlJRsI4","video": "" },
    "Impala": {"image": "M03OCZvYSxY","video": "" },
    "Jackrabbit": {"image": "o4kAhL2X3Wk","video": "" },
    "Jackson’s Chameleon": {"image": "nMJKAXHBLLI","video": "" },
    "Jaguar": {"image": "gkBthB89xMs","video": "" },
    "Jellyfish": {"image": "5fhcbkOPhwA","video": "" },
    "Kangaroo": {"image": "2f33ykzzPCU","video": "" },
    "Kestrel": {"image": "UfyDkU1uVX0","video": "" },
    "Kingfisher": {"image": "7xQW7I9flYk","video": "" },
    "Koala": {"image": "CIMk0FSOrAE","video": "" },
    "Komodo Dragon": {"image": "W0-3v369lrE","video": "" },
    "Ladybug": {"image": "Ap0alm8xpxw","video": "" },
    "Leatherback Sea Turtle": {"image": "Xchp9dzP0ao","video": "" },
    "Lemur": {"image": "83gB_koMuvA","video": "" },
    "Leopard": {"image": "3TwThGdEUZA","video": "uxPMj-lq_aA" },
    "Lion": {"image": "UxHol6SwLyM","video": "" },
    "Llama": {"image": "yt39XjxwGUE","video": "" },
    "Lobster": {"image": "p1D68SxmdtY","video": "" },
    "Macaque": {"image": "gYSHsshVZLM","video": "" },
    "Macaroni Penguin": {"image": "Cj7cnWptYiI","video": "" },
    "Manatee": {"image": "udSP7GCxw3w","video": "" },
    "Manta Ray": {"image": "Syzn3nfkYE4","video": "" },
    "Marmot": {"image": "iyg1Otnket8","video": "" },
    "Moose": {"image": "MVIqwQvkwG4","video": "" },
    "North American Black Bear": {"image": "lWHvAw1Inbs","video": "" },
    "Northern Cardinal": {"image": "Yu_ejF2s_dI","video": "" },
    "Nudibranch": {"image": "pymDKmTB7wk","video": "" },
    "Octopus": {"image": "dW0gfo__uU8","video": "" },
    "Orang-utan": {"image": "8_5sEk7Ay18","video": "" },
    "Ostrich": {"image": "qeGHu5Jdy5s","video": "" },
    "Otter": {"image": "","video": "" },
    "Oyster": {"image": "","video": "" },
    "Painted Turtle": {"image": "w4tjvHHcwbg","video": "" },
    "Platypus": {"image": "Vv019m_ClpY","video": "" },
    "Polar Bear": {"image": "Ec_ygZTIv_0","video": "" },
    "Porcupine": {"image": "na4VeTI5c-0","video": "" },
    "Proboscis Monkey": {"image": "H0x10qmw9Zc","video": "" },
    "Quetzal": {"image": "cvO95LohoQg","video": "" },
    "Quokka": {"image": "4cT6YwMkHyg","video": "" },
    "Rabbit": {"image": "KvHT4dltPEQ","video": "" },
    "Red Panda": {"image": "e8t9o3eJ36o","video": "" },
    "Reef Shark": {"image": "ZEr3XTwFxxE","video": "" },
    "Robin": {"image": "3lGi0BXJ1W0","video": "" },
    "Roseate Spoonbill": {"image": "WP0ZP9pFywU","video": "" },
    "Salamander": {"image": "CcZW_zuuCGk","video": "" },
    "Scarlet Macaw": {"image": "vIx55PnjL58","video": "" },
    "Sea Anemone": {"image": "2cU7jvnjYhk","video": "" },
    "Sea Dragon": {"image": "6NSWCndscrE","video": "" },
    "Seahorse": {"image": "n6cvkHh0xmE","video": "" },
    "Skunk": {"image": "jG8eaA5Iq3A","video": "" },
    "Sloth": {"image": "E1UfNaIQMSY","video": "" },
    "Squid": {"image": "j8BRxbtTwTQ","video": "" },
    "Stork": {"image": "biJCd2N-1ms","video": "" },
    "Tapir": {"image": "ZgJVo64oBUM","video": "" },
    "Tiger": {"image": "Fbdr6gXJBVY","video": "" },
    "Tiger Shark": {"image": "GBDkr3k96DE","video": "" },
    "Tree Frog": {"image": "JLMEZxBcXCU","video": "" },
    "Vervet Monkey": {"image": "rTEt2xxdOvI","video": "" },
    "Vicuña": {"image": "OXPFrEwRlv0","video": "" },
    "Vulture": {"image": "X_focRRR0Uw","video": "" },
    "Walrus": {"image": "h13Y8vyIXNU","video": "" },
    "Warthog": {"image": "6GOGynHxL74","video": "" },
    "Whale Shark": {"image": "Abj_zUko6Mg","video": "" },
    "White-Faced Capuchin": {"image": "5UGhVm_YDdg","video": "" },
    "Wolf": {"image": "1AIYdIb3O5M","video": "" },
    "Xerus": {"image": "WuZKOVtnvC8","video": "" },
    "Yak": {"image": "PQgD2Mjrjpw","video": "" },
    "Yellowfin Tuna": {"image": "jKbhB5Qh-9k","video": "" },
    "Zebra": {"image": "UgidX4V13Gc","video": "" },
    "Zebra Finch": {"image": "M9YOf_w6uiE","video": "" }
}

module.exports = MEDIA;