const animalsList = [
    "Adelie_Penguin",
    "Agama_Lizard", 
    "Albatross", 
    "Alligator",
    "Alpaca", 
    "Arctic Fox", 
    "Assassin Bug", 
    "Axolotl", 
    "Baboon", 
    "Bald Eagle", 
    "Banana Ball Python", 
    "Barn Owl", 
    "Bearded Vulture",  
    "Beaver", 
    "Bee", 
    "Bengal Tiger", 
    "Bison", 
    "Black Rhinoceros", 
    "Black-Footed Ferret", 
    "Blue-Ringed Octopus", 
    "Bobcat", 
    "Box Turtle", 
    "Burrowing Owl", 
    "Camel", 
    "Caribou", 
    "Cheetah", 
    "Clownfish", 
    "Coral Snake",
    "Crocodile",
    "Deer",
    "Desert Tortoise",
    "Dingo",
    "Dolphin",
    "Dragonfly",
    "Earthworm",
    "Eel",
    "Elephant",
    "Elephant Seal",
    "Elk",
    "Emu",
    "Flamingo",
    "Flounder",
    "Fox",
    "Frog",
    "Fruit Bat",
    "Galapagos Tortoise",
    "Gazelle",
    "Gecko",
    "Giraffe",
    "Glass Frog",
    "Golden Lion Tamarin",
    "Gorilla",
    "Hammerhead Shark",
    "Hawaiian Goose",
    "Heron",
    "Hippopotamus",
    "Howler Monkey",
    "Hummingbird",
    "Humpback Whale",
    "Ibex",
    "Ibis",
    "Iguana",
    "Impala",
    "Jackrabbit",
    "Jackson’s Chameleon",
    "Jaguar",
    "Jellyfish",
    "Kangaroo",
    "Kestrel",
    "King Cobra",
    "Kingfisher",
    "Kiwi",
    "Koala",
    "Komodo Dragon",
    "Ladybug",
    "Leatherback Sea Turtle",
    "Lemur",
    "Leopard",
    "Lion",
    "Llama",
    "Lobster",
    "Macaque",
    "Macaroni Penguin",
    "Manatee",
    "Manta Ray",
    "Marmot",
    "Moose",
    "Narwhal",
    "North American Black Bear",
    "Northern Cardinal",
    "Nudibranch",
    "Numbat",
    "Octopus",
    "Orang-utan",
    "Ostrich",
    "Otter",
    "Oyster",
    "Painted Turtle",
    "Panther",
    "Parrotfish",
    "Platypus",
    "Polar Bear",
    "Porcupine",
    "Proboscis Monkey",
    "Quagga",
    "Quetzal",
    "Quokka",
    "Rabbit",
    "Red Panda",
    "Reef Shark",
    "Robin",
    "Roseate Spoonbill",
    "Salamander",
    "Scarlet Macaw",
    "Sea Anemone",
    "Sea Dragon",
    "Seahorse",
    "Skunk",
    "Sloth",
    "Squid",
    "Stork",
    "Tapir",
    "Tiger",
    "Tiger Shark",
    "Tree Frog",
    "Tropicbird",
    "Uakari",
    "Umbrellabird",
    "Utonagan",
    "Vervet Monkey",
    "Vicuña",
    "Vulture",
    "Walrus",
    "Warthog",
    "Whale Shark",
    "White-Faced Capuchin",
    "Wolf",
    "X-Ray Tetra",
    "Xerus",
    "Xoloitzcuintli",
    "Yak",
    "Yellow Anaconda",
    "Yellowfin Tuna",
    "Zebra",
    "Zebra Finch",
    "Zebra Mussels",
    "Zebu"
];  

export default animalsList;