/** populate animals relation in db with icons for user badges*/

INSERT INTO animals(common_name, photo)
VALUES
('Adelie Penguin', '/images/adeliepenguin.png'), 
('Agama Lizard', '/images/agamalizard.jpg'), 
('Albatross', '/images/albatross.png'), 
('Alligator', '/images/alligator.png'), 
('Alpaca', '/images/alpaca.png'), 
('Arctic Fox', '/images/arcticfox.jpg'), 
('Assassin Bug', '/images/assassinbug.jpg'), 
('Axolotl', '/images/axolotl.gif'), 
('Baboon', '/images/baboon.jpg'), 
('Bald Eagle', '/images/baldeagle.jpg'), 
('Banana Ball Python', '/images/bananaballpython.png'), 
('Barn Owl', '/images/barnowl.png'), 
('Bearded Vulture', '/images/beardedvulture.jpg'), 
('Beaver', '/images/beaver.jpg'), 
('Bee', '/images/bee.png'), 
('Bengal Tiger', '/images/bengaltiger.png'), 
('Bison', '/images/bison.png'), 
('Black Rhinoceros', '/images/blackrhinoceros.png'), 
('Black-Footed Ferret', '/images/blackfootedferret.png'), 
('Blue-Ringed Octopus', '/images/blueringedoctopus.jpg'), 
('Bobcat', '/images/bobcat.jpg'), 
('Box Turtle', '/images/boxturtle.gif'), 
('Burrowing Owl', '/images/burrowingowl.png'), 
('Camel', '/images/camel.png'), 
('Caribou', '/images/caribou.png'), 
('Cheetah', '/images/cheetah.jpg'), 
('Clownfish', '/images/clownfish.jpg'), 
('Coral Snake', '/images/coralsnake.gif'), 
('Crocodile', '/images/crocodile.png'), 
('Deer', '/images/deer.png'), 
('Desert Tortoise', '/images/deserttortoise.png'), 
('Dingo', '/images/dingo.png'), 
('Dolphin', '/images/dolphin.jpg'), 
('Dragonfly', '/images/dragonfly.jpg'), 
('Earthworm', '/images/earthworm.png'), 
('Eel', '/images/eel.jpg'), 
('Elephant', '/images/elephant.gif'), 
('Elephant Seal', '/images/elephantseal.jpg'), 
('Elk', '/images/elk.png'), 
('Emu', '/images/emu.gif'), 
('Flamingo', '/images/flamingo.png'), 
('Flounder', '/images/flounder.jpg'), 
('Fox', '/images/fox.jpg'), 
('Frog', '/images/frog.png'), 
('Fruit Bat', '/images/fruitbat.jpg'), 
('Galapagos Tortoise', '/images/galapagostortoise.gif'), 
('Gazelle', '/images/gazelle.jpg'), 
('Gecko', '/images/gecko.png'), 
('Giraffe', '/images/giraffe.gif'), 
('Glass Frog', '/images/glassfrog.gif'), 
('Golden Lion Tamarin', '/images/goldenliontamarin.jpg'), 
('Gorilla', '/images/gorilla.jpg'), 
('Hammerhead Shark', '/images/hammerhead.png'), 
('Hawaiian Goose', '/images/hawaiiangoose.png'), 
('Heron', '/images/heron.gif'), 
('Hippopotamus', '/images/hippopotamus.png'), 
('Howler Monkey', '/images/howlermonkey.jpg'), 
('Hummingbird', '/images/hummingbird.png'), 
('Humpback Whale', '/images/humpbackwhale.gif'), 
('Ibex', '/images/ibex.png'), 
('Ibis', '/images/ibis.jpg'), 
('Iguana', '/images/iguana.png'), 
('Impala', '/images/impala.png'), 
('Jackrabbit', '/images/jackrabbit.gif'), 
('Jackson’s Chameleon', '/images/jacksonschameleon.gif'), 
('Jaguar', '/images/jaguar.jpg'), 
('Jellyfish', '/images/jellyfish.png'), 
('Kangaroo', '/images/kangaroo.jpg'), 
('Kestrel', '/images/kestrel.png'), 
('King Cobra', '/images/kingcobra.png'), 
('Kingfisher', '/images/kingfisher.jpg'), 
('Kiwi', '/images/kiwi.png'), 
('Koala', '/images/koala.png'), 
('Komodo Dragon', '/images/komododragon.jpg'), 
('Ladybug', '/images/ladybug.jpg'), 
('Leatherback Sea Turtle', '/images/leatherbackseaturtle.jpg'), 
('Lemur', '/images/lemur.png'), 
('Leopard', '/images/leopard.png'), 
('Lion', '/images/lion.png'), 
('Llama', '/images/llama.png'), 
('Lobster', '/images/lobster.jpg'), 
('Macaque', '/images/macaque.png'), 
('Macaroni Penguin', '/images/macaronipenguin.png'), 
('Manatee', '/images/manatee.jpg'), 
('Manta Ray', '/images/mantaray.png'), 
('Marmot', '/images/marmot.png'), 
('Moose', '/images/moose.png'), 
('Narwhal', '/images/narwahl.png'), 
('North American Black Bear', '/images/northamericanblackbear.jpg'), 
('Northern Cardinal', '/images/northerncardinal.png'), 
('Nudibranch', '/images/nudibranch.jpg'), 
('Numbat', '/images/numbat.png'), 
('Octopus', '/images/octopus.png'), 
('Orang-utan', '/images/orangutan.jpg'), 
('Ostrich', '/images/ostrich.png'), 
('Otter', '/images/otter.png'), 
('Oyster', '/images/oyster.png'), 
('Painted Turtle', '/images/paintedturtle.gif'), 
('Panther', '/images/panther.png'), 
('Parrotfish', '/images/parrotfish.jpeg'), 
('Platypus', '/images/platypus.png'), 
('Polar Bear', '/images/polarbear.png'), 
('Porcupine', '/images/porcupine.jpg'), 
('Proboscis Monkey', '/images/proboscismonkey.webp'), 
('Quetzal', '/images/quetzal.png'), 
('Quokka', '/images/quokka.jpeg'), 
('Rabbit', '/images/rabbit.gif'), 
('Red Panda', '/images/redpanda.jpg'), 
('Reef Shark', '/images/reefshark.jpg'), 
('Robin', '/images/robin.png'), 
('Roseate Spoonbill', '/images/roseatespoonbill.jpg'), 
('Salamander', '/images/salamander.png'), 
('Scarlet Macaw', '/images/scarletmacaw.png'), 
('Sea Anemone', '/images/seaanemone.png'), 
('Sea Dragon', '/images/seadragon.png'), 
('Seahorse', '/images/seahorse.jpg'), 
('Skunk', '/images/skunk.png'), 
('Sloth', '/images/sloth.png'), 
('Squid', '/images/squid.jpg'), 
('Stork', '/images/stork.png'), 
('Tapir', '/images/tapir.gif'), 
('Tiger', '/images/tiger.png'), 
('Tiger Shark', '/images/tigershark.jpg'), 
('Tree Frog', '/images/treefrog.jpg'), 
('Tropicbird', '/images/tropicbird.png'), 
('Uakari', '/images/uakari.jpeg'), 
('Umbrellabird', '/images/umbrellabird.png'), 
('Vervet Monkey', '/images/vervetmonkey.jpg'), 
('Vicuña', '/images/vicuna.png'), 
('Vulture', '/images/vulture.png'), 
('Walrus', '/images/walrus.jpg'), 
('Warthog', '/images/warthog.png'), 
('Whale Shark', '/images/whaleshark.png'), 
('White-Faced Capuchin', '/images/whitefacedcapuchin.png'), 
('Wolf', '/images/wolf.jpg'), 
('X-Ray Tetra', '/images/xraytetra.png'), 
('Xerus', '/images/xerus.gif'), 
('Yak', '/images/yak.png'), 
('Yellow Anaconda', '/images/yellowanaconda.png'), 
('Yellowfin Tuna', '/images/yellowfintuna.png'), 
('Zebra', '/images/zebra.png'), 
('Zebra Finch', '/images/zebrafinch.jpeg'), 
('Zebra Mussels', '/images/zebramussels.png'), 
('Zebu', '/images/zebu.jpeg');

INSERT INTO parents(username, password, first_name, last_name, email, access_code) 
VALUES('demoParent', 'abc123$%^', 'demo', 'parent', 'demo@parent.com', 3456);