INSERT INTO animals(common_name, photo)
VALUES
('Adelie_Penguin', '/images/penguin.png'), 
('Agama_Lizard', '/images/penguin.png'), 
('Albatross', '/images/penguin.png'), 
('Alligator', '/images/penguin.png'), 
('Alpaca', '/images/penguin.png'), 
('Arctic Fox', '/images/penguin.png'), 
('Assassin Bug', '/images/penguin.png'), 
('Axolotl', '/images/penguin.png'), 
('Baboon', '/images/penguin.png'), 
('Bald Eagle', '/images/penguin.png'), 
('Banana Ball Python', '/images/penguin.png'), 
('Barn Owl', '/images/penguin.png'), 
('Bearded Vulture', '/images/penguin.png'), 
('Beaver', '/images/penguin.png'), 
('Bee', '/images/penguin.png'), 
('Bengal Tiger', '/images/penguin.png'), 
('Bison', '/images/penguin.png'), 
('Black Rhinoceros', '/images/penguin.png'), 
('Black-Footed Ferret', '/images/penguin.png'), 
('Blue-Ringed Octopus', '/images/penguin.png'), 
('Bobcat', '/images/penguin.png'), 
('Box Turtle', '/images/penguin.png'), 
('Burrowing Owl', '/images/penguin.png'), 
('Camel', '/images/penguin.png'), 
('Caribou', '/images/penguin.png'), 
('Cheetah', '/images/penguin.png'), 
('Clownfish', '/images/penguin.png'), 
('Coral Snake', '/images/penguin.png'), 
('Crocodile', '/images/penguin.png'), 
('Deer', '/images/penguin.png'), 
('Desert Tortoise', '/images/penguin.png'), 
('Dingo', '/images/penguin.png'), 
('Dolphin', '/images/penguin.png'), 
('Dragonfly', '/images/penguin.png'), 
('Earthworm', '/images/penguin.png'), 
('Eel', '/images/penguin.png'), 
('Elephant', '/images/penguin.png'), 
('Elephant Seal', '/images/penguin.png'), 
('Elk', '/images/penguin.png'), 
('Emu', '/images/penguin.png'), 
('Flamingo', '/images/penguin.png'), 
('Flounder', '/images/penguin.png'), 
('Fox', '/images/penguin.png'), 
('Frog', '/images/penguin.png'), 
('Fruit Bat', '/images/penguin.png'), 
('Galapagos Tortoise', '/images/penguin.png'), 
('Gazelle', '/images/penguin.png'), 
('Gecko', '/images/penguin.png'), 
('Giraffe', '/images/penguin.png'), 
('Glass Frog', '/images/penguin.png'), 
('Golden Lion Tamarin', '/images/penguin.png'), 
('Gorilla', '/images/penguin.png'), 
('Hammerhead Shark', '/images/penguin.png'), 
('Hawaiian Goose', '/images/penguin.png'), 
('Heron', '/images/penguin.png'), 
('Hippopotamus', '/images/penguin.png'), 
('Howler Monkey', '/images/penguin.png'), 
('Hummingbird', '/images/penguin.png'), 
('Humpback Whale', '/images/penguin.png'), 
('Ibex', '/images/penguin.png'), 
('Ibis', '/images/penguin.png'), 
('Iguana', '/images/penguin.png'), 
('Impala', '/images/penguin.png'), 
('Jackrabbit', '/images/penguin.png'), 
('Jackson’s Chameleon', '/images/penguin.png'), 
('Jaguar', '/images/penguin.png'), 
('Jellyfish', '/images/penguin.png'), 
('Kangaroo', '/images/penguin.png'), 
('Kestrel', '/images/penguin.png'), 
('King Cobra', '/images/penguin.png'), 
('Kingfisher', '/images/penguin.png'), 
('Kiwi', '/images/penguin.png'), 
('Koala', '/images/penguin.png'), 
('Komodo Dragon', '/images/penguin.png'), 
('Ladybug', '/images/penguin.png'), 
('Leatherback Sea Turtle', '/images/penguin.png'), 
('Lemur', '/images/penguin.png'), 
('Leopard', '/images/penguin.png'), 
('Lion', '/images/penguin.png'), 
('Llama', '/images/penguin.png'), 
('Lobster', '/images/penguin.png'), 
('Macaque', '/images/penguin.png'), 
('Macaroni Penguin', '/images/penguin.png'), 
('Manatee', '/images/penguin.png'), 
('Manta Ray', '/images/penguin.png'), 
('Marmot', '/images/penguin.png'), 
('Moose', '/images/penguin.png'), 
('Narwhal', '/images/penguin.png'), 
('North American Black Bear', '/images/penguin.png'), 
('Northern Cardinal', '/images/penguin.png'), 
('Nudibranch', '/images/penguin.png'), 
('Numbat', '/images/penguin.png'), 
('Octopus', '/images/penguin.png'), 
('Orang-utan', '/images/penguin.png'), 
('Ostrich', '/images/penguin.png'), 
('Otter', '/images/penguin.png'), 
('Oyster', '/images/penguin.png'), 
('Painted Turtle', '/images/penguin.png'), 
('Panther', '/images/penguin.png'), 
('Parrotfish', '/images/penguin.png'), 
('Platypus', '/images/penguin.png'), 
('Polar Bear', '/images/penguin.png'), 
('Porcupine', '/images/penguin.png'), 
('Proboscis Monkey', '/images/penguin.png'), 
('Quetzal', '/images/penguin.png'), 
('Quokka', '/images/penguin.png'), 
('Rabbit', '/images/penguin.png'), 
('Red Panda', '/images/penguin.png'), 
('Reef Shark', '/images/penguin.png'), 
('Robin', '/images/penguin.png'), 
('Roseate Spoonbill', '/images/penguin.png'), 
('Salamander', '/images/penguin.png'), 
('Scarlet Macaw', '/images/penguin.png'), 
('Sea Anemone', '/images/penguin.png'), 
('Sea Dragon', '/images/penguin.png'), 
('Seahorse', '/images/penguin.png'), 
('Skunk', '/images/penguin.png'), 
('Sloth', '/images/penguin.png'), 
('Squid', '/images/penguin.png'), 
('Stork', '/images/penguin.png'), 
('Tapir', '/images/penguin.png'), 
('Tiger', '/images/penguin.png'), 
('Tiger Shark', '/images/penguin.png'), 
('Tree Frog', '/images/penguin.png'), 
('Tropicbird', '/images/penguin.png'), 
('Uakari', '/images/penguin.png'), 
('Umbrellabird', '/images/penguin.png'), 
('Vervet Monkey', '/images/penguin.png'), 
('Vicuña', '/images/penguin.png'), 
('Vulture', '/images/penguin.png'), 
('Walrus', '/images/penguin.png'), 
('Warthog', '/images/penguin.png'), 
('Whale Shark', '/images/penguin.png'), 
('White-Faced Capuchin', '/images/penguin.png'), 
('Wolf', '/images/penguin.png'), 
('X-Ray Tetra', '/images/penguin.png'), 
('Xerus', '/images/penguin.png'), 
('Yak', '/images/penguin.png'), 
('Yellow Anaconda', '/images/penguin.png'), 
('Yellowfin Tuna', '/images/penguin.png'), 
('Zebra', '/images/penguin.png'), 
('Zebra Finch', '/images/penguin.png'), 
('Zebra Mussels', '/images/penguin.png'), 
('Zebu', '/images/penguin.png')